#!/bin/bash
set -e

echo "🧹 Running cleanup script for PrimaryButton.tsx ..."

# Ensure git index is healthy
git fsck --full || true
git gc --prune=now || true
git reflog expire --expire=now --all || true

# Define the expected location
TARGET="components/ui/PrimaryButton.tsx"

# Create the folder if missing
mkdir -p "$(dirname "$TARGET")"

# If file doesn’t exist, create a fresh default PrimaryButton.tsx
if [ ! -f "$TARGET" ]; then
  cat > "$TARGET" <<'EOF'
import * as React from "react";

interface PrimaryButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  children: React.ReactNode;
}

export default function PrimaryButton({ children, ...props }: PrimaryButtonProps) {
  return (
    <button
      {...props}
      className="px-4 py-2 rounded-2xl bg-blue-600 text-white hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {children}
    </button>
  );
}
EOF

  echo "✅ Created new $TARGET"
  
  # Stage and commit the new file immediately
  git add "$TARGET"
  git commit -m "chore: add PrimaryButton.tsx auto-generated by cleanup script"
else
  echo "ℹ️ $TARGET already exists — no new file created."
fi

# Finally, repair git index just in case
git add -A
git commit -m "chore: auto-cleanup run" || echo "ℹ️ No changes to commit."

echo "🚀 Cleanup finished!"
