#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

changed_files="$(git diff --name-only HEAD@{1} HEAD)"

if echo "$changed_files" | grep -qE "package(-lock)?\.json"; then
  echo "📦 Dependencies changed — running npm install..."
  npm install
fi
