#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run placeholder test
if npm test; then
  # Success
  echo -e "\033[32m✅ Pre-commit checks passed\033[0m"
else
  # Failure
  echo -e "\033[31m❌ Pre-commit checks failed. Commit aborted.\033[0m"
  exit 1
fi
