name: Redeploy Vercel (Deploy Hook)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy hook
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          echo "Calling Vercel Deploy Hook…"
          curl -i -X POST "$HOOK"
